# This workflow will run unit tests

name: Run Unit Tests
on:
  pull_request:
  workflow_dispatch:

jobs:
  py_build_tests:
    uses: neongeckocom/.github/.github/workflows/python_build_tests.yml@master
  docker_build_tests:
    uses: neongeckocom/.github/.github/workflows/docker_build_tests.yml@master
  unit_tests:
    strategy:
      matrix:
        python-version: [ 3.9, "3.10", "3.11" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get install espeak-ng
          python -m pip install --upgrade pip wheel
          pip install -r requirements/requirements.txt -r requirements/test_requirements.txt
      - name: Test TTS
        run: |
          pytest tests/test_tts.py --junitxml=tests/tts-test-results.xml
      - name: Upload TTS test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: tests/tts-test-results.xml
        if: ${{ always() }}
